### ISSUE TITLE
请问怎么单独安装xp？

### ISSUE THREAD

**Issue by DelmarHuang** [keatonlao/tiddlywiki-xp#1]
你好，我的tiddlywiki里已经安装了很多插件了，也有蛮多笔记了。想请问下该怎么只安装xp需要的插件及相关的插件？而不是直接下载完整的html😂这样我的笔记和原来的插件就没了。麻烦你了，谢谢

**Comment by keatonlao** [comment]
你好！只需把 XP  中的所有插件（[plugins/PluginforSingleFileVersion.zip](https://github.com/keatonlao/tiddlywiki-xp/blob/master/plugins/PluginforSingleFileVersion.zip)）拖到你的维基中就可以了。

鉴于你的提问，我把这个问题写到教程文档里了：

- [我想使用 TiddlyWiki XP？](https://keatonlao.github.io/tiddlywiki-xp/#%E6%88%91%E6%83%B3%E4%BD%BF%E7%94%A8%20TiddlyWiki%20XP%EF%BC%9F)
