### ISSUE TITLE
桌面版太微导入项目报错

### ISSUE THREAD

**Issue by linxin2020** [keatonlao/tiddlywiki-xp#10]
我使用的是桌面版 TidGi v0.8.0，导入 tiddlywiki-xp_Full.html 报错，尝试过 tiddlywiki-xp_Minimal.html ，问题相同。

> 该HTML文件无法用于创建WIKI
> CANNOT READ PROPERTIES OF UNDEFINED (READING 'REPLACE')

![image](https://github.com/keatonlao/tiddlywiki-xp/assets/46699328/368e2804-3259-4873-9ea0-6616dddc0162)

**Comment by keatonlao** [comment]
你好，我在 [TidGi v0.8.1-prerelease6](https://github.com/tiddly-gittly/TidGi-Desktop/releases/tag/v0.8.1-prerelease6) 上可以导入。

---

你可以试试使用空白版，再把 PluginforSingleFileVersion.zip 中的所有插件拖进太记。
