### ISSUE TITLE
Getting Things Done插件的清理机会把todolist的其他代办事项清理掉

### ISSUE THREAD

**Issue by king0billy** [keatonlao/tiddlywiki-xp#11]
如题  我用$:/plugins/kookma/todolist生成的tid被这段代码删了，这段代码应该只删除gtd插件生产的数据吧
`<$button class="py-btn xp-gtd-btn">
    清理机
    <$vars junkFilter="[prefix[$:/todolist/data/status/]removeprefix[$:/todolist/data/status]addprefix[$:]!is[tiddler]] [tag[GettingThingsDone]get[list]enlist-input[]!is[tiddler]]">
        <$list filter="[subfilter<junkFilter>count[]!match[0]]" variable="ignore">
            <$list filter=<<junkFilter>> variable="junkItem">
                <$vars junkItemSuffix={{{ [<junkItem>removeprefix[$:/]] }}}>
                    <$action-deletetiddler $filter="[prefix[$:/todolist/data]suffix<junkItemSuffix>]"/>
                    <$list filter=<<gtd-quadrant>> variable="qList">
                        <$action-listops $tiddler=<<qList>> $subfilter="-[<junkItem>]"/>
                    </$list>
                </$vars>
            </$list>
            <$action-sendmessage $message="tm-notify" $param="$:/language/Notifications/CompleteCleanup"/>
        </$list>
        <$list filter="[subfilter<junkFilter>count[]match[0]]">
            <$action-sendmessage $message="tm-notify" $param="$:/language/Notifications/NoCleaningRequired"/>
        </$list>
    </$vars>
</$button>`

**Comment by king0billy** [comment]
四象限的删除功能无法使用（搜索下的正常），最好有个删除条目的回收站，像todolist那样用archived来保存

**Comment by king0billy** [comment]
![image](https://github.com/keatonlao/tiddlywiki-xp/assets/52921954/d067946f-5d09-4efb-9b15-975a5de7c8a6)
超过九条条目就wu无法正常显示

**Comment by keatonlao** [comment]
@king0billy 
1. 已复现 bug，确实会删除 Todolist 的数据。静待推送更新，不会马上更新，最近有事。
2. 四象限只能显示最近 8 条数据，更多数据点击象限标题，进入单象限模式查看。
3. 单象限中的删除按钮，我这里是可用的。
4. 未做归档功能，可能也不会做。任务完成即归档，不删除即可，删除就代表你此时想让信息化为灰烬。如果你的意思是，删除后保留30天再删除，我也不会做。如果确实有需求，可能得你自己撸起袖子开干。

感谢您的热心反馈！

**Comment by king0billy** [comment]
我想把@Gk0Wk的sidebar-resizer插件和您的leftOpenTab插件融合一下 ，
方法是把压缩的sidebar-resizer插件json的一行代码 用gpt转换成多行的易于阅读的格式 （但是多层转义无法保留）   然后进行很多文本替换  
目前遇到了一个问题就是不知道怎样将代码中的   ”“冒号  内的   ”“冒号   正确地多层转义 成///“  （最多有三个///）
比如
``        "text": {
            "tiddlers": {
                "$:/plugins/ljl/leftbar-resizer/LICENSE": {  ``
转换成
``    "text": "{\"tiddlers\":{\"$:/plugins/Gk0Wk/sidebar-resizer/LICENSE\" ``   
导致import的插件是空白的
如果您有空的话可以指点一下下吗  代码如下


``[
    {
        "author": "ljl",
        "dependents": "",
        "description": "Use the cursor to resize the width of the sidebar.",
        "list": "readme LICENSE",
        "name": "Sidebar Resizer",
        "plugin-type": "plugin",
        "text": {
            "tiddlers": {
                "$:/plugins/ljl/leftbar-resizer/LICENSE": {
                    "title": "$:/plugins/ljl/leftbar-resizer/LICENSE",
                    "text": "MIT License\n\nCopyright (c) 2021 Ke Wang (ljl in GitHub)\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the \"Software\"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.\n",
                    "type": "text/plain"
                },
                "$:/plugins/ljl/leftbar-resizer/readme": {
                    "title": "$:/plugins/ljl/leftbar-resizer/readme",
                    "text": "\\define lingo-base() $:/language/ThemeTweaks/\n\n<$list filter=\"[[$:/language]get[text]removeprefix[$:/languages/]else[en-GB]]\" variable=\"lang\">\n    <$list filter=\"[<lang>search[zh]]\">\n        [ljl!]会在侧边栏的左侧边缘添加一个可拖动的边框，当鼠标移动到左侧边缘时会看到这个边框。拖动这个边框可以改变侧边栏的宽度，拖动到靠近窗口右侧边缘时就会自动收起侧边栏。\n\n        原理是更改[[$:/themes/tiddlywiki/vanilla/metrics/sidebarwidth]]的值。\n\n        注意：首先请将 <$link to=\"$:/themes/tiddlywiki/vanilla/options/sidebarlayout\"><<lingo Options/SidebarLayout>></$link> 调整为`fluid-fixed`，本插件才可生效。\n\n        <$button set=\"$:/themes/tiddlywiki/vanilla/options/sidebarlayout\" setTo=\"fluid-fixed\">点击设置<<lingo Options/SidebarLayout>></$button>\n\n        > 本插件使用灵活而强大的 <$text text=\"TiddlyWiki\" /> 开发框架 [[Tiddly.ModernDev|https://github.com/tiddly-gittly/Modern.TiddlyDev]]\n    </$list>\n\n    <$list filter=\"[<lang>!search[zh]]\">\n        A draggable border is added to the left edge of the sidebar, which will be visible when the mouse is moved to the left edge. Dragging this border will change the width of the sidebar, and it will automatically close the sidebar when dragged near the right edge of the window.\n\n        The principle is to change the value of [[$:/themes/tiddlywiki/vanilla/metrics/sidebarwidth]].\n\n        Note: First, please adjust <$link to=\"$:/themes/tiddlywiki/vanilla/options/sidebarlayout\"><<lingo Options/SidebarLayout>></$link> to `fluid-fixed` for this plugin to take effect.\n\n        <$button set=\"$:/themes/tiddlywiki/vanilla/options/sidebarlayout\" setTo=\"fluid-fixed\">Click to adjust<<lingo Options/SidebarLayout>></$button>\n\n        > This plugin uses the flexible and powerful <$text text=\"TiddlyWiki\" /> development framework [[Tiddly.ModernDev|https://github.com/tiddly-gittly/Modern.TiddlyDev]]\n    </$list>\n</$list>\n",
                    "type": "text/plain"
                },
                "$:/plugins/ljl/leftbar-resizer/resizer": {
                    "title": "$:/plugins/ljl/leftbar-resizer/resizer",
                    "tags": "$:/tags/LeftBarSegment",
                    "text": "<div id=\"ljl-leftbar-resize-area\"></div>\n"
                },
                "$:/plugins/ljl/leftbar-resizer/style.css": {
                    "title": "$:/plugins/ljl/leftbar-resizer/style.css",
                    "text": "<$reveal state=\"$:/config/LeftOpenTab/Status\" type=\"match\" text=\"hide\">\n    .tc-leftbar-scrollable {\n        display: none;\n    }\n</$reveal>\n\ndiv#ljl-leftbar-resize-area {\n    height: 100vh;\n    width: 10px;\n    position: absolute;\n    top: 0;\n    left: -5px;\n    cursor: ew-resize;\n    transition: all {{$:/config/AnimationDuration}}ms;\n}\n\ndiv#ljl-leftbar-resize-area:hover {\n    background: <<colour primary>>;\n}\n",
                    "tags": "$:/tags/Stylesheet",
                    "type": "text/vnd.tiddlywiki"
                },
                "$:/plugins/ljl/leftbar-resizer/hook.js": {
                    "title": "$:/plugins/ljl/leftbar-resizer/hook.js",
                    "module-type": "startup",
                    "type": "application/javascript",
                    "Modern.TiddlyDev#Origin": "hook.ts",
                    "text": "\"use strict\";var __defProp=Object.defineProperty,__getOwnPropDesc=Object.getOwnPropertyDescriptor,__getOwnPropNames=Object.getOwnPropertyNames,__hasOwnProp=Object.prototype.hasOwnProperty,__export=(e,t)=>{for(var o in t)__defProp(e,o,{get:t[o],enumerable:!0})},__copyProps=(t,o,r,n)=>{if(o&&\"object\"==typeof o||\"function\"==typeof o)for(let e of __getOwnPropNames(o))__hasOwnProp.call(t,e)||e===r||__defProp(t,e,{get:()=>o[e],enumerable:!(n=__getOwnPropDesc(o,e))||n.enumerable});return t},__toCommonJS=e=>__copyProps(__defProp({},\"__esModule\",{value:!0}),e),hook_exports={},name=(__export(hook_exports,{after:()=>after,name:()=>name,platforms:()=>platforms,startup:()=>startup,synchronous:()=>synchronous}),module.exports=__toCommonJS(hook_exports),\"ljl-leftbar-resizer\"),platforms=[\"browser\"],after=[\"render\"],synchronous=!0,startup=()=>{let r=!1,t=null;const n=document[\"body\"],i=e=>{r=!0,e instanceof PointerEvent&&n.setPointerCapture(e.pointerId),n.style.userSelect=\"none\",n.style.MozUserSelect=\"none\"},s=e=>{r&&(r=!1,e instanceof PointerEvent&&n.releasePointerCapture(e.pointerId),n.style.userSelect=\"auto\",n.style.MozUserSelect=\"auto\")};$tw.hooks.addHook(\"th-page-refreshed\",()=>{var e;function o(e){$tw.wiki.setText(\"$:/config/LeftOpenTab/Status\", void 0, void 0, \"hide\"), s(e)}null!=t&&t.ownerDocument.contains(t)||(t=document.querySelector(\"#ljl-leftbar-resize-area\"))&&(r=!1,e=(t=window.event)=>{if(r&&t)return t.preventDefault(),t.stopPropagation(),t.stopImmediatePropagation(),t.returnValue=!1,requestAnimationFrame(()=>{var e=100-t.clientX/window.innerWidth*100;if(80<e)return!1;window.innerWidth-t.clientX<100?(window.innerWidth - t.clientX < 100 ? ($tw.wiki.setText(\"$:/xp/leftopentab/metrics/width\", void 0, void 0, 3e2 +\"px\"), o(t)) : $tw.wiki.setText(\"$:/xp/leftopentab/metrics/width\", void 0, void 0, e*window.innerWidth/100 + \"px\")}),!1},t.addEventListener(\"dblclick\",o),window.PointerEvent?(t.addEventListener(\"pointerdown\",i),n.addEventListener(\"pointerup\",s),n.addEventListener(\"blur\",s),n.addEventListener(\"pointermove\",e,!0)):(t.addEventListener(\"mousedown\",i),n.addEventListener(\"mouseup\",s),n.addEventListener(\"blur\",s),n.addEventListener(\"mousemove\",e,!0),t.addEventListener(\"touchstart\",i),n.addEventListener(\"touchcancel\",s),n.addEventListener(\"touchend\",s),n.addEventListener(\"touchmove\",e,!0)))})};"
                }
            }
        },
        "title": "$:/plugins/ljl/leftbar-resizer",
        "type": "application/json",
        "version": "0.0.1"
    }
]
``

**Comment by king0billy** [comment]
> @king0billy
> 
> 1. 已复现 bug，新 TW 版本中确实会删除 Todolist 的数据。静待推送更新，不会马上更新，最近有事。
> 2. 四象限只能显示最近 8 条数据，更多数据点击象限标题，进入单象限模式查看。
> 3. 单象限中的删除按钮，我这里是可用的。
> 4. 未做归档功能，可能也不会做。任务完成即归档，不删除即可，删除就代表你此时想让信息化为灰烬。如果你的意思是，删除后保留30天再删除，我也不会做。如果确实有需求，可能得你自己撸起袖子开干。
> 
> 感谢您的热心反馈！

2.我想的是可以加入一个滚轮？应该很简单 如果我实在觉得别扭和有需求 我再去研究一下
3.四象限的日常优先级清除功能我以为是删除条目了 ，是我误会了 ，不是bug。btw优先级只有四级吗不能自定义吗
4.todolist有归档功能 但是归档了也不能从归档archived中恢复到done（翻了一下projectify的issue，也有人提了https://github.com/NicolasPetton/Projectify/issues/70#issuecomment-831644593 但是也没实现 估计挺难）
我想要的是数据最大程度的易于保留和恢复...留坑以后我自己研究一下吧

**Comment by king0billy** [comment]
![image](https://github.com/keatonlao/tiddlywiki-xp/assets/52921954/3f112824-9036-424e-80e2-28f2cb617e8b) 
一个小bug 关闭所有的右columns项目后红圈所画的两个区域都丧失了再打开双column的功能 
只能用ctrl+alt+c打开projectify的inbox 才能恢复这两个区域功能
而在我的电脑上需要不定次数的多次按ctrl+alt+c才能打开  也许是和projectify的inbox冲突

**Comment by king0billy** [comment]
更新vis.js从4.17.0到5.3.1会导致整个程序崩溃无法进入... （不知道是tidgi的bug还是xp的bug）
Unhandled Promise Rejection
Error:  [1;31mError executing boot module $:/plugins/felixhayashi/vis/vis.js: "Global assignment is not allowed within modules on node."
undefined[0m
    at Object.next (C:/Users/22427/AppData/Local/tidgi/app-0.8.1-prerelease6/resources/app.asar/.webpack/main/index.js:2:1955845)

**Comment by keatonlao** [comment]
@king0billy
Q1：想把插件 sidebar-resizer 和 leftOpenTab 进行功能融合，文本替换
时冒号内的冒号如何转义？
A1：插件融合是个好主意，但我不明白为何会出现转义的问题。你是如何阅读代码并修改融合代码的？如果是我，我会下载插件源码，没有源码就将 json 插件包解压为可在代码编辑器中打开进行阅读修改的源码文件。融合完再打包为 json 插件包。推荐利用 TW nodejs 版本进行开发测试。只要你搞懂 sidebar-resizer，应该很简单啊，就是拖动时调整相关的数值。

Q2：一个小 bug 关闭所有的右栏项目后丧失了再打开双栏的功能。
A2：用户必须把鱼放进右故事河（右栏）中，才能呈现双栏，才能隐藏显示右栏。右河里没鱼，就看不见河。

Q3：TW5.3.1 中更新 vis.js 导致整个程序崩溃无法进入... （不知道是tidgi的bug还是xp的bug）
A3：通常来讲是插件之间互不兼容导致的，这个需要自己慢慢排查。你必须做出选择，要么回退用旧版，要么使用新版删掉其不兼容的插件。几乎没有人愿意去魔改不兼容的插件。普通用户的处事态度是遇坑他就避开，开发者的处事态度是遇坑他有时间和动力那么他来填上。

Q4：我想给 GTD 四象限界面下的每个象限加上滚动栏。
A4：四象限界面的设定就是固定展示每个象限最近的 8 条任务。可以通过修改 css 多展示几条，比如 10 条。默认不会加滚动栏，你喜欢滚动栏的话，可以自己定制。

Q5：GTD 的优先级只有四级，如何自定义？
A5：不能自定义，因为 GTD 采用四象限法则，所以只有四个优先级。滴答清单也只有四个优先级。GTD 不做「收集箱」模式，只做了直观高效的四象限模式。

**Comment by king0billy** [comment]
插件源码我只能找到”tiddlers“压缩成一行的，因为作者的github上没放出来，只能从插件的json文件获取。请问能用什么压缩和解压，我用的是chatgpt
![image](https://github.com/keatonlao/tiddlywiki-xp/assets/52921954/9fb03acf-191f-4a1e-b246-5ccde381e7e2)

**Comment by king0billy** [comment]
点击leftopentab插件的tiddler下的contents 出现这种bug  重启无法消除
![Uploading image.png…]()

**Comment by king0billy** [comment]
gtd里集成的todolist是阉割的吗   怎么找不到archive呀

**Comment by keatonlao** [comment]
Bug 已修复，新版已上线。
