### ISSUE TITLE
LeftOpenTab插件  点击right column下的标签页无法定位到对应标签页

### ISSUE THREAD

**Issue by king0billy** [keatonlao/tiddlywiki-xp#12]
LeftOpenTab插件有问题， 点击right column下的标签页无法定位到对应标签页

**Comment by keatonlao** [comment]
新版中已修复。

**Comment by king0billy** [comment]
LeftOpenTab0.3.0 点击right column下的标签页还是没效果啊

**Comment by keatonlao** [comment]
@king0billy 你用的现版本中的 $:/plugins/xp/rivers 吗？我在[主站点](https://keatonlao.github.io/tiddlywiki-xp/)上没发现问题呐~

**Comment by king0billy** [comment]
我现在看到到CPL上的rivers还是0.0.1
![image](https://github.com/keatonlao/tiddlywiki-xp/assets/52921954/f787df96-c446-4623-a0e5-56d050cfd47c)

**Comment by keatonlao** [comment]
@king0billy 事情多版本号我忘记改了，你重新安装一下吧。

**Comment by king0billy** [comment]
> @king0billy 你用的现版本中的 $:/plugins/xp/rivers 吗？我在[主站点](https://keatonlao.github.io/tiddlywiki-xp/)上没发现问题呐~

主站上根本没有把tidder发送到右栏的按钮啊。点下巴栏里的双栏也没有效果

**Comment by keatonlao** [comment]
@king0billy 查看工具栏那个 divert 按钮。

**Comment by king0billy** [comment]
已经在资源管理器下删除了rivers重装还是不行
![2024-03-10 20-01-31](https://github.com/keatonlao/tiddlywiki-xp/assets/52921954/81627d26-bd67-4887-ac83-b9a59ff33bda)
我觉得可能是有什么插件冲突了。请问应该怎么排查。PS：一直用的tidgi，tidgi预装了很多插件
另外开了右栏之后主题不一致，看起来很别扭

**Comment by keatonlao** [comment]
@king0billy 你可以这样排查插件冲突，将太记默认插件 5 个为一组导入到 xp 中，直到出现异常的一组，再将这 5 个插件逐个导入进行检查。

太记默认插件导出方法：

1. 下载仓库 https://github.com/tiddly-gittly/Tiddlywiki-NodeJS-Github-Template。tiddlers 文件夹下以 `$__plugins` 开头的即为默认插件。
2. 在太记默认模板中，通过 CPL 安装插件 `$:/plugins/xp/aggregation`，通过 `$:/BatchExport` 选择筛选器表达式 `[plugin-type[plugin]] -$:/core` 将默认插件导出。

**Comment by keatonlao** [comment]
@king0billy 关于样式冲突，你可以打开浏览器调试工具（`ctrl-shift-I`），查看那个样式在生效，对冲突样式进行修改。

在 xp 中没有异常，所以我猜测是启用双栏的样式表和太记中的样式有所冲突。

**Comment by king0billy** [comment]
用CPL上的 $:/plugins/oeyoews/notebook-theme-sidebar-resizer 插件, 你的左侧边栏已经可以拖动调整宽度了。[这是论坛issue](https://talk.tiddlywiki.org/t/new-tiddlywiki-sidebar-resizer/8705/48)
希望可以整合进xp！

**Comment by king0billy** [comment]
左侧边栏可拖动调整宽度：
[$:/plugins/oeyoews/notebook-theme-sidebar-resizer插件下载链接](https://tiddlywiki-starter-kit.vercel.app/#%24%3A%2Fplugins%2Foeyoews%2Fnotebook-theme-sidebar-resizer)

**Comment by king0billy** [comment]
我还是没有解决右栏定位这个问题。如果您有空的话可以检查一下我的wiki文件夹吗 
含 tiddlers+ shadows的 测试用例 https://1drv.ms/u/s!AkIa8srN94mPg7QRSYy7_cBUrZC-mA?e=HiVXsW
a json file that doesn't have my shadow tiddlers: https://1drv.ms/u/s!AkIa8srN94mPg7RPyxuyIoNnlOS3sg?e=IlT1fW

> @king0billy 你可以这样排查插件冲突，将太记默认插件 5 个为一组导入到 xp 中，直到出现异常的一组，再将这 5 个插件逐个导入进行检查。
> 
> 太记默认插件导出方法：
> 
> 1. 下载仓库 [https://github.com/tiddly-gittly/Tiddlywiki-NodeJS-Github-Template。tiddlers](https://github.com/tiddly-gittly/Tiddlywiki-NodeJS-Github-Template%E3%80%82tiddlers) 文件夹下以 `$__plugins` 开头的即为默认插件。
> 2. 在太记默认模板中，通过 CPL 安装插件 `$:/plugins/xp/aggregation`，通过 `$:/BatchExport` 选择筛选器表达式 `[plugin-type[plugin]] -$:/core` 将默认插件导出。

**Comment by keatonlao** [comment]
> 我还是没有解决右栏定位这个问题。

删掉影子文件：`$:/xp/ui/PageTemplate/story2`。重装插件出现问题，看一眼文件列表，那些不是 config 文件的影子条目，要删除。

**Comment by Hydrowood0** [comment]
> > 我还是没有解决右栏定位这个问题。
> 
> 删掉影子文件：`$:/xp/ui/PageTemplate/story2`。重装插件出现问题，看一眼文件列表，那些不是 config 文件的影子条目，要删除。

删除 `$:/xp/ui/PageTemplate/story2` 之后, 点Right Column下的条目Left Column会focus到不相关?的地方.  Right Column还是没变化.
然后要删除哪些shadows条目呀? 删几千条怕出问题.

> 重装插件出现问题

没看懂您表达什么意思.  是让我删除 `$:/xp/ui/PageTemplate/story2` 之后重装rivers吗? 我这样做了还是和上面一样的没效果
![image](https://github.com/keatonlao/tiddlywiki-xp/assets/172965706/569c66c1-8a85-4990-9806-83ec47d7b9ce)
![image](https://github.com/keatonlao/tiddlywiki-xp/assets/172965706/57073742-e56e-4972-a23f-824236f0213a)

**Comment by keatonlao** [comment]
> 没看懂您表达什么意思

1. 在 empty 版本上安装插件没问题，那应该就没问题。
1. 当安装新版本时，应该彻底删除旧插件，使用新版中的代码。
