### ISSUE TITLE
服务器版仓库，用于作为初始模板

### ISSUE THREAD

**Issue by linonetwo** [keatonlao/tiddlywiki-xp#15]
我准备在 https://github.com/tiddly-gittly 组织里放一份 https://raw.kkgithub.com/keatonlao/tiddlywiki-xp/master/version/tiddlywiki-xp_Server.zip 的解压后 + 预装 CPL + tw-mobile-sync 插件的版本，以便作为可选的初始模板在太记桌面端和移动端里供选择。类似 https://github.com/tiddly-gittly/Tiddlywiki-NodeJS-Github-Template 。

不知道你的工作流是什么样，是从服务器版打包出 HTML，还是反过来。如果你是先有服务器版的话，其实可以直接提供一个服务器版仓库，最好能预装上述两个插件，这样我就能直接使用了，也不需要隔段时间想起来了手动去更新，你觉得呢？

**Comment by keatonlao** [comment]
我这边可以创建一个 XP 服务器版仓库用于模板。我需要在 [tiddlywiki-xp_Server.zip](https://raw.kkgithub.com/keatonlao/tiddlywiki-xp/master/version/tiddlywiki-xp_Server.zip) 上做一些插件删减和去冗余（没有启用的插件）。我的想法是模板中只保留基础和常用的插件，其余插件用户根据自己需求去扩展。

**Comment by linonetwo** [comment]
是应该这样，然后麻烦你装上 CPL，然后用 CPL 装一下 tw-mobile-sync 插件，太记移动端需要它提供的 HTTP API 才能下载模板，目前是这样，之后也可以看看能不能用官方 API。

**Comment by keatonlao** [comment]
@linonetwo 我看 https://github.com/tiddly-gittly/Tiddlywiki-NodeJS-Github-Template 模板中，插件是以 json 的格式存在于 tiddlers 文件夹下。所以我现在不知道，这个模板，插件是以源代码的格式还是 json 的格式存在并被使用？

**Comment by linonetwo** [comment]
都用 JSON 插件的方式放 tiddlers 文件夹里，方便用 CPL 更新。CPL 在界面上点按钮只能更新 tiddlers 文件夹里的东西，旧的 plugins 文件夹现在弃用了，因为需要用户去打开文件夹看一堆 json 文件甚至插件源码，而很多人其实连 JSON 是什么都不知道，不能一键更新的话，他们用的插件就永远不会更新了。

**Comment by linonetwo** [comment]
https://github.com/tiddly-gittly/TidGi-Mobile 最新版已经可以下载使用太记桌面端的默认模板了，而且内置了 tiddlywiki-xp 作为可添加的教程

**Comment by keatonlao** [comment]
@linonetwo 你看一下是否可以。https://github.com/keatonlao/tiddlywiki-xp-nodejs-template

**Comment by linonetwo** [comment]
我用太记在服务器上部署了 https://tiddlywiki-xp-nodejs-template.cpolar.top/ 

还有一个 PR，其它应该可以了，谢了

**Comment by linonetwo** [comment]
最新版可用了 https://talk.tidgi.fun/topic/129
