### ISSUE TITLE
XP River 多栏布局使得移动端侧边栏被遮挡

### ISSUE THREAD

**Issue by linonetwo** [keatonlao/tiddlywiki-xp#16]
![图片](https://github.com/keatonlao/tiddlywiki-xp/assets/3746270/e295d878-8f51-4d7c-bcf3-810911896a42)

```css
z-index: inherit;
    background: transparent;
```

这两个覆盖了侧边栏样式，会导致其被遮挡
![图片](https://github.com/keatonlao/tiddlywiki-xp/assets/3746270/c861c34f-64da-4a62-bc98-5fa4aa26f7ba)

正常应该是这样的

![图片](https://github.com/keatonlao/tiddlywiki-xp/assets/3746270/ad849d65-294d-4a06-b86b-6ecc9faa2e12)

我使用的主题是

https://github.com/tiddly-gittly/itonnote-theme/blob/e552202ac25b285685c483ae443e018fbd9fc668/src/itonnote/base.tid#L448-L460

**Comment by linonetwo** [comment]
还有这个

![图片](https://github.com/keatonlao/tiddlywiki-xp/assets/3746270/f5c94b2d-7373-4021-9029-9a777077cbf8)

```
    padding-right: 2em;
```

也会导致移动端上右边多出一个间隔

![图片](https://github.com/keatonlao/tiddlywiki-xp/assets/3746270/1d66b76b-d8f9-476c-ba95-7257b2772c15)

**Comment by keatonlao** [comment]
@linonetwo 好的，我会在下个版本中，在移动端禁用冲突样式。

**Comment by keatonlao** [comment]
@linonetwo 新版已上线。我已同步更新了模板 [tiddlywiki-xp-nodejs-template](https://github.com/keatonlao/tiddlywiki-xp-nodejs-template/)。
