### ISSUE TITLE
bug: 点击 $:/FilterSearch 卡死无响应

### ISSUE THREAD

**Issue by king0billy** [keatonlao/tiddlywiki-xp#18]
才发现没导出 aggregation插件，您在cpl重装一个试试，bug还是一样的。
含 tiddlers+ shadows的 测试用例 https://1drv.ms/u/s!AkIa8srN94mPg7QRSYy7_cBUrZC-mA?e=HiVXsW

a json file that doesn't have my shadow tiddlers: https://1drv.ms/u/s!AkIa8srN94mPg7RPyxuyIoNnlOS3sg?e=IlT1fW

**Comment by keatonlao** [comment]
我看了有反应。反应半天是因为你给到 `$:/config/xp/aggregation/MainFilter` 的过滤器，其结果太多（6839 matches）。这几乎会把你 156 个插件（包含 core）中的所有条目列出来了。

```
[all[shadows+tiddlers]!tag[todo]!tag[$:/plugins/nico/projectify/tags/Category]!prefix[Todolist - Archived Items]!prefix[$:/todolist/data/state/gtd]!suffix[.png]!creator[HydroWood]!creator[TidGi User]!creator[HydroWood's phone]]
```

我想不通你这个过滤器的操作目的，所以，我只能建议你灵活地使用过滤器。

1. 如果你只是想导出此过滤器的结果，大可不必放到聚合视图中去加载，直接在高级搜索的筛选里面操作。
1. 如果你想利用聚合视图查阅条目内容：
- 你得考虑范围，通常操作范围是 `all[tiddlers]` 而非 `all[shadows+tiddlers]`。因为 shadows 是插件里面的默认条目。
- 或者开启聚合视图中的翻页（Show pagination），避免一次性加载所有结果。

**Comment by keatonlao** [comment]
我看了有反应。反应半天是因为你给到 `$:/config/xp/aggregation/MainFilter` 的过滤器，其结果太多（6839 matches）。这几乎会把你 156 个插件（包含 core）中的所有条目列出来了。

```
[all[shadows+tiddlers]!tag[todo]!tag[$:/plugins/nico/projectify/tags/Category]!prefix[Todolist - Archived Items]!prefix[$:/todolist/data/state/gtd]!suffix[.png]!creator[HydroWood]!creator[TidGi User]!creator[HydroWood's phone]]
```

我想不通你这个过滤器的操作目的，所以，我只能建议你灵活地使用过滤器。

1. 如果你只是想导出此过滤器的结果，大可不必放到聚合视图中去加载，直接在高级搜索的筛选里面操作。
1. 如果你想利用聚合视图查阅条目内容：
- 你得考虑范围，通常操作范围是 `all[tiddlers]` 而非 `all[shadows+tiddlers]`。因为 shadows 是插件里面的默认条目。
- 或者开启聚合视图中的翻页（Show pagination），避免一次性加载所有结果。
