### ISSUE TITLE
new private journal 默认生成的标题异常

### ISSUE THREAD

**Issue by dofine** [keatonlao/tiddlywiki-xp#2]
![CleanShot 2022-02-23 at 07 55 08@2x](https://user-images.githubusercontent.com/440101/155279973-711a6fb1-403e-43c2-8661-ca1206c51c0c.png)
2022/0223 这个样式感觉不符合习惯，希望可以自定义标题……（还是其实可以但我没找到地方）？

**Comment by keatonlao** [comment]
1. 你重新拉取仓库更新。
2. 然后将所有插件拖到你的维基中，导入有更新的插件。
3. 然后配置条目 **$:/config/NewJournal/Title** 即可。入口在 控制面板 -> 信息 -> 基本 -> 新日志条目的名称。

> 你可以参照默认按钮 **$:/core/ui/Buttons/new-journal** 制作按钮。这样更方便自己自定义。
