### ISSUE TITLE
希望 $:/FilterBuilder 能发布为独立插件

### ISSUE THREAD

**Issue by linonetwo** [keatonlao/tiddlywiki-xp#21]
在 https://talk.tiddlywiki.org/t/10349/4 在讨论这个。我想到我也希望在别的插件里嵌入这个筛选器可视化构建器，但希望它作为依赖尽可能轻量。

有没有可能将它以及相关的 CSS 发布为独立插件？或者能否授权我使用这些代码在 https://github.com/tiddly-gittly/ 里开个新仓库把它发布为插件？这样我还能给它加上中文翻译。

**Comment by keatonlao** [comment]
@linonetwo 非常抱歉，我最近没时间和心思搞这些事。不回复也是一种回复，毕竟回复了也等于没回复。

XP 中有你喜欢的东西，直接拿去就行了，不需要我授权，也不需要告知我。

> XP 中我没有写任何声明，是因为教程中的很多内容都来自网上，来于网络归于网络。任何人都可以随便使用，不存在侵权这回事。我们就是在前人的基础上不断发展。

**Comment by linonetwo** [comment]
谢了，我已经开始用了
