### ISSUE TITLE
xp插件中还有您的私人内容

### ISSUE THREAD

**Issue by longguzzz** [keatonlao/tiddlywiki-xp#3]
您好，在xp插件里似乎还有一些您的私人内容，包括
![image](https://user-images.githubusercontent.com/96779663/159009060-663d07f5-8098-4cf0-8b38-19c97ea5a0d7.png)
![image](https://user-images.githubusercontent.com/96779663/159009094-e7679971-d52b-4359-9c50-6c51bd6b598d.png)
![image](https://user-images.githubusercontent.com/96779663/159009118-6a341e41-a104-404d-be68-d8e170b6e02b.png)
这些貌似由于和插件在一起的，删除之后会自动恢复

**Comment by keatonlao** [comment]
肝了几天，内容已更新。用最新的版本吧。

- [使用 TiddlyWiki XP？](https://keatonlao.gitee.io/tiddlywiki-xp/#%E6%88%91%E6%83%B3%E4%BD%BF%E7%94%A8%20TiddlyWiki%20XP%EF%BC%9F)

---

对了，导致你无法删除的罪魁祸首，可能是 tiddlymap（给这些普通条目添加了字段 tmap.id）。正常情况下，是可以直接删除这些用户条目的。
