### ISSUE TITLE
希望教程能打包成插件

### ISSUE THREAD

**Issue by linonetwo** [keatonlao/tiddlywiki-xp#4]
这样我可以把它也预置进我的发行版里，更方便新手。

**Comment by linonetwo** [comment]
还有你可以把一些教程发到知乎之类的地方，来吸引新人呀

**Comment by keatonlao** [comment]
1. 大神，我认真思考了你的建议，但将教程打包成插件的方式可能行不通。我的想法是，教程和教程里涉及的插件要作为一个整体呈现给新人朋友。也就是说，tiddlywiki-xp_Tutorials.html 整个文档本身就是教程。
1. 不敢在知乎上随便发帖：我对 TiddlyWiki 的理解不深，xp 教程可以说是我分享的个人学习笔记，不专业。

**Comment by linonetwo** [comment]
也有道理，或许将整个 HTML 作为 Obsidian 那样的 Help Vault 提供给用户体验才最好，之后我在太记里试试。这样相当于预置了教程+相关插件了。

**Comment by linonetwo** [comment]
其实你写得挺专业了，现在国内介绍 TW 详细用法的不多，反而到处都是 Ob、Notion 用户在介绍用法刷屏，他们倒也没在意过介绍 Ob 介绍得不专业嘛
