### ISSUE TITLE
Can you update the Tekkan plug in used in Tiddlywiki XP to feature from Tekkan one

### ISSUE THREAD

**Issue by arunnbabu81** [keatonlao/tiddlywiki-xp#7]
This is the demo of Tekkan One https://ibnishak.github.io/Tekkan/Tekkan%20Demo.html- which is not a TW plug in. It has more features compared to the version in TW XP. Can you update the Tekkan in XP to add those feature also. The relevant tiddlers must be in this github repo - https://github.com/ibnishak/Tekkan

**Comment by keatonlao** [comment]
I'm sorry, but I won't do that. I suggest you ask the original author.

**Comment by arunnbabu81** [comment]
@keatonlao the original author is no longer maintaining it. Thats why I was asking you because you are the only one who have recently worked on Tekan.

**Comment by keatonlao** [comment]
@arunnbabu81 I don't actually use tekan in tw. The plug-in in XP is purely a demonstration to give you an idea.
