### ISSUE TITLE
Use query macros in filter builder

### ISSUE THREAD

**Issue by arunnbabu81** [keatonlao/tiddlywiki-xp#8]
https://talk.tiddlywiki.org/t/query-macros-in-rr-tw5-github-io/1830

https://rr-tw5.github.io/#Queries%2C%20transclusions%2C%20and%20other%20macros

Is there a way to use these query macros from rr-tw5 wiki in the filter builder in TW XP - https://keatonlao.github.io/tiddlywiki-xp/#%24%3A%2FFilterBuilder

**Comment by keatonlao** [comment]
I have added the Query to `$:/FilterBuilder` and `$:/AdvancedSearch`.

**Comment by arunnbabu81** [comment]
Thank you @keatonlao for adding queries
