### ISSUE TITLE
aggregation插件可以让标签筛选改为筛选表达式筛选吗？

### ISSUE THREAD

**Issue by dongrentianyu** [keatonlao/tiddlywiki-xp#9]
![UWV0Y$97 5PWT$~{~H)NW3L](https://user-images.githubusercontent.com/109711900/228768684-aa8e39af-6cc3-4c67-8a54-c2181c27148e.jpg)

我想要把这个固定下来，但我是用字段的值筛选出条目的。我不想通过加标签的方式。加标签会让这个标签失效，或者说标签就变成了无意义的。不如用字段筛选更方便。

**Comment by dongrentianyu** [comment]
aggregation插件一直没更新的样子。因为现在想把这个内容放到另一个插件里去使用。但一直没更新就只有手动添加了。

https://github.com/tiddly-gittly/intention-tower-knowledge-graph/issues/16

**Comment by dongrentianyu** [comment]
我研究了一下代码。发现没有留筛选器的位置，而是默认引用另一个筛选器。

```

\define aggr-has-tids()
[tag<aggregationTag>!has[draft.of]limit[1]]
\end
```

其中`$:/aggregation/macros/general`条目里有上面代码。

```
\define aggregation-filtersearch(fields:"tbl-expand title", class:"w-100", state:"aggregation-general", paginationButton:"yes", rowsButton:"no", viewButton:"yes", searchClass:"xp-search-aggregation", cardTemplate:"$:/aggregation-card-template", tocTemplate, promptTiddler:"$:/aggregation/prompt")
\import $:/aggregation/macros/general
\whitespace trim
<$list filter=<<aggr-has-tids>> emptyMessage="{{$promptTiddler$}}" variable="ignore">
```

然后在`$:/aggregation/macros`里就调用了上面的筛选器。这就是为什么没有留筛选器的位置。我觉得这个设计不太好。不能方便其他插件调用。不过也有可能有什么用法我没注意到。

我还是希望能简单调用自定义的筛选器，用起来更方便。

**Comment by dongrentianyu** [comment]
我要改版本号吗？

**Comment by dongrentianyu** [comment]
有一个小问题，宏里面有一个state参数。但我发现`$:/plugins/linonetwo/intention-tower-knowledge-graph/ViewTemplate/TaskDynamicTable`是作为模板参数传入的。

![image](https://github.com/keatonlao/tiddlywiki-xp/assets/109711900/538b5717-ec08-4a6b-b137-c98a7bf2ba6d)

![image](https://github.com/keatonlao/tiddlywiki-xp/assets/109711900/6afcb455-f73c-4dab-96a6-f7c2227f13ac)

也就是容易出现上面的情况，就是在一个项目里列出的表格内容，在另一个项目里也会同样列出。因为背后所使用的state参数是一样的。如何保证使用的参数是不一样的呢？要用变量。可state能用变量传入吗？要用什么变量呢？

**Comment by dongrentianyu** [comment]
![image](https://github.com/keatonlao/tiddlywiki-xp/assets/109711900/b37bb18c-ab93-45d7-8a5b-9891c5a9c386)

就直接变成默认的了。

不过我觉得好像这样也可以。用户不用每建一个项目就去调整列出的字段。嗯，先这样好了。

**Comment by keatonlao** [comment]
新版 aggregation 0.5.0 已发布。

将筛选表达式传给 aggregation 宏，即可聚合起来。宏定义详见 $:/aggregation/macros。

###############

@dongrentianyu 调用  aggregation 宏时，指定一个唯一的 state，多个聚合视图就不会出现错误的同步操作。

**Comment by dongrentianyu** [comment]
非常感谢。
